SQLALCHEMY_DATABASE_URI = 'sqlite:///snork.db'
SECRET_KEY="testing with this"
RECAPTCHA_PUBLIC_KEY = '6LdavPYSAAAAAGxSMcoGhPQ_V3Bvmdz5Gi9E0t6B'
RECAPTCHA_PRIVATE_KEY = '6LdavPYSAAAAALAcpPDgKIEYrLEPafe5M_wAkxlX'
BASEURL = "http://127.0.0.1:5000"
PORT = 5000
DEBUG = True
WHOOSH_BASE = 'search'